#!/usr/bin/env perl

use v5.36;
use Test::Most;

use_ok('App::GHGen::PerlCustomizer', qw(generate_custom_perl_workflow));

# ── Lint step present by default ──────────────────────────────────────────

subtest 'lint step generated by default' => sub {
    my $yaml = generate_custom_perl_workflow({});

    like($yaml, qr/Lint and syntax check/, 'lint step is present by default');
    like($yaml, qr/shell: perl \{0\}/,     'step uses perl {0} shell');
    like($yaml, qr/File::Find/,            'step uses File::Find for cross-platform discovery');
    like($yaml, qr/-Mstrict.*-Mwarnings.*-c/s, 'step enables strict and warnings during syntax check');
};

# ── Lint step absent when disabled ────────────────────────────────────────

subtest 'lint step absent when enable_linter => 0' => sub {
    my $yaml = generate_custom_perl_workflow({ enable_linter => 0 });

    unlike($yaml, qr/Lint and syntax check/, 'lint step is absent');
    unlike($yaml, qr/shell: perl \{0\}/,     'perl {0} shell not used');
};

# ── Lint step runs before tests ────────────────────────────────────────────

subtest 'lint step comes before Run tests' => sub {
    my $yaml = generate_custom_perl_workflow({});

    my $lint_pos  = index($yaml, 'Lint and syntax check');
    my $tests_pos = index($yaml, 'Run tests');

    ok($lint_pos  > 0, 'lint step is present');
    ok($tests_pos > 0, '"Run tests" step is present');
    ok($lint_pos < $tests_pos, 'lint step comes before Run tests');
};

# ── warnings::unused step absent by default ───────────────────────────────

subtest 'unused-variable step absent by default' => sub {
    my $yaml = generate_custom_perl_workflow({});

    unlike($yaml, qr/Check for unused variables/, 'unused step absent by default');
    unlike($yaml, qr/warnings::unused/,           'warnings::unused not installed by default');
};

# ── warnings::unused step present when enabled ────────────────────────────

subtest 'unused-variable step generated when enable_linter_unused => 1' => sub {
    my $yaml = generate_custom_perl_workflow({ enable_linter_unused => 1 });

    like($yaml, qr/Check for unused variables/, 'unused step is present');
    like($yaml, qr/warnings::unused/,           'installs warnings::unused');
    like($yaml, qr/continue-on-error: true/,    'step is non-blocking');
};

# ── warnings::unused step runs on latest+ubuntu only ──────────────────────

subtest 'unused-variable step is conditioned on latest perl + ubuntu' => sub {
    my $yaml = generate_custom_perl_workflow({ enable_linter_unused => 1 });

    like($yaml, qr/ubuntu-latest/, 'step limited to ubuntu-latest');
    # The conditional references the highest Perl version in the matrix
    like($yaml, qr/matrix\.perl == '[\d.]+'/, 'step limited to a specific Perl version');
};

# ── warnings::unused step comes after tests and before Perl::Critic ───────

subtest 'unused-variable step position is correct' => sub {
    my $yaml = generate_custom_perl_workflow({
        enable_linter_unused => 1,
        enable_critic        => 1,
    });

    my $unused_pos = index($yaml, 'Check for unused variables');
    my $tests_pos  = index($yaml, 'Run tests (Windows)');
    my $critic_pos = index($yaml, 'Run Perl::Critic');

    ok($unused_pos > 0, 'unused step present');
    ok($tests_pos  > 0, '"Run tests (Windows)" present');
    ok($critic_pos > 0, '"Run Perl::Critic" present');
    ok($tests_pos  < $unused_pos, 'unused step comes after Run tests (Windows)');
    ok($unused_pos < $critic_pos, 'unused step comes before Run Perl::Critic');
};

# ── Both linter options disabled independently ─────────────────────────────

subtest 'options are independent' => sub {
    my $yaml_neither = generate_custom_perl_workflow({
        enable_linter        => 0,
        enable_linter_unused => 0,
    });
    unlike($yaml_neither, qr/Lint and syntax check/,   'neither lint step');
    unlike($yaml_neither, qr/Check for unused variables/, 'nor unused step');

    my $yaml_unused_only = generate_custom_perl_workflow({
        enable_linter        => 0,
        enable_linter_unused => 1,
    });
    unlike($yaml_unused_only, qr/Lint and syntax check/,    'no lint step');
    like($yaml_unused_only,   qr/Check for unused variables/, 'but unused step present');
};

done_testing();
